import 'package:get/state_manager.dart';
import 'package:last_minutes_deal/deals/domain/entities/category_chip_entity.dart';
import 'package:last_minutes_deal/deals/domain/entities/deal_entity.dart';

class DealHomeController extends GetxController {
  final RxList<CategoryEntity> categoryList = <CategoryEntity>[
    CategoryEntity(name: 'All', isSelected: true),
    CategoryEntity(name: 'Hotel'),
    CategoryEntity(name: 'Resort'),
    CategoryEntity(name: 'Villa'),
    CategoryEntity(name: 'Camping'),
  ].obs;

  void selectCategory(int index) {
  for (int i = 0; i < categoryList.length; i++) {
    final bool isSelected=i == index;
    categoryList[i] = CategoryEntity(
      name: categoryList[i].name,
      isSelected:isSelected ,
    );
  }
  categoryList.refresh();
}
  final RxList<DealEntity> hotels = <DealEntity>[
    DealEntity(
      id: 'hotel_1',
      name: 'Hotel Horizon',
      imageUrl: 'assets/images/home_images/hotel_1.jpg',
      location: 'Lonavala',
      rating: 4.0,
      reviewCount: 23,
      pricePerNight: 2680,
      category: 'Hotel',
      isFavorite: true,
      isLiveDeal: true,
    ),
    DealEntity(
      id: 'hotel_2',
      name: 'Hotel O Regency',
      imageUrl: 'assets/images/home_images/hotel_2.jpg',
      location: 'Pune',
      rating: 3.1,
      reviewCount: 70,
      pricePerNight: 1400,
      category: 'Hotel',
      isFavorite: false,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'hotel_3',
      name: 'The Heritage Stay',
      imageUrl: 'assets/images/home_images/hotel_3.jpg',
      location: 'Mahabaleshwar',
      rating: 4.5,
      reviewCount: 112,
      pricePerNight: 3200,
      category: 'Hotel',
      isFavorite: true,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'hotel_4',
      name: 'Urban Suites',
      imageUrl: 'assets/images/home_images/hotel_4.jpg',
      location: 'Mumbai',
      rating: 4.2,
      reviewCount: 88,
      pricePerNight: 4100,
      category: 'Hotel',
      isFavorite: false,
      isLiveDeal: true,
    ),
  ].obs;

  final RxList<DealEntity> resorts = <DealEntity>[
    DealEntity(
      id: 'resort_1',
      name: 'Lagoon Palm Resort',
      imageUrl: 'assets/images/home_images/resort_1.jpg',
      location: 'Goa',
      rating: 4.5,
      reviewCount: 94,
      pricePerNight: 8500,
      category: 'Resort',
      isFavorite: true,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'resort_2',
      name: 'Azure Water Villa Resort',
      imageUrl: 'assets/images/home_images/resort_2.jpg',
      location: 'Maldives',
      rating: 4.9,
      reviewCount: 156,
      pricePerNight: 35000,
      category: 'Resort',
      isFavorite: false,
      isLiveDeal: true,
    ),
    DealEntity(
      id: 'resort_3',
      name: 'Seaside Breeze Resort',
      imageUrl: 'assets/images/home_images/resort_3.jpg',
      location: 'Kovalam',
      rating: 4.7,
      reviewCount: 118,
      pricePerNight: 12000,
      category: 'Resort',
      isFavorite: false,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'resort_4',
      name: 'Splash World Park & Resort',
      imageUrl: 'assets/images/home_images/resort_4.jpg',
      location: 'Lonavala',
      rating: 4.2,
      reviewCount: 63,
      pricePerNight: 6800,
      category: 'Resort',
      isFavorite: true,
      isLiveDeal: true,
    ),
  ].obs;

  final RxList<DealEntity> villas = <DealEntity>[
    DealEntity(
      id: 'villa_1',
      name: 'Villas_24',
      imageUrl: 'assets/images/home_images/villa_1.jpg',
      location: 'Lonavala',
      rating: 4.6,
      reviewCount: 87,
      pricePerNight: 20000,
      category: 'Villa',
      isFavorite: true,
      isLiveDeal: true,
    ),
    DealEntity(
      id: 'villa_2',
      name: 'Palace Villa',
      imageUrl: 'assets/images/home_images/villa_2.jpg',
      location: 'Mumbai',
      rating: 3.7,
      reviewCount: 28,
      pricePerNight: 25000,
      category: 'Villa',
      isFavorite: false,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'villa_3',
      name: 'Ekostay Palm Villa',
      imageUrl: 'assets/images/home_images/villa_3.jpg',
      location: 'Alibaug',
      rating: 4.8,
      reviewCount: 104,
      pricePerNight: 18500,
      category: 'Villa',
      isFavorite: true,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'villa_4',
      name: 'Sunset Grand Villa',
      imageUrl: 'assets/images/home_images/villa_4.jpg',
      location: 'Karjat',
      rating: 4.3,
      reviewCount: 45,
      pricePerNight: 22000,
      category: 'Villa',
      isFavorite: false,
      isLiveDeal: true,
    ),
  ].obs;

  final RxList<DealEntity> campings = <DealEntity>[
    DealEntity(
      id: 'camp_1',
      name: 'A-Frame Wooden Huts',
      imageUrl: 'assets/images/home_images/camp_1.jpg',
      location: 'Pawna Lake',
      rating: 4.5,
      reviewCount: 62,
      pricePerNight: 2500,
      category: 'Camping',
      isFavorite: true,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'camp_2',
      name: 'Forest Treehouse Camp',
      imageUrl: 'assets/images/home_images/camp_2.jpg',
      location: 'Wayanad',
      rating: 4.7,
      reviewCount: 89,
      pricePerNight: 4200,
      category: 'Camping',
      isFavorite: false,
      isLiveDeal: true,
    ),
    DealEntity(
      id: 'camp_3',
      name: 'Luxury Glamping Bell Tent',
      imageUrl: 'assets/images/home_images/camp_3.jpg',
      location: 'Alibaug',
      rating: 4.6,
      reviewCount: 41,
      pricePerNight: 3100,
      category: 'Camping',
      isFavorite: true,
      isLiveDeal: true,
    ),
    DealEntity(
      id: 'camp_4',
      name: 'Pine Forest Safari Camp',
      imageUrl: 'assets/images/home_images/camp_4.jpg',
      location: 'Manali',
      rating: 4.8,
      reviewCount: 115,
      pricePerNight: 3800,
      category: 'Camping',
      isFavorite: false,
      isLiveDeal: false,
    ),
    DealEntity(
      id: 'camp_5',
      name: 'Luxury Dome Pod Stay',
      imageUrl: 'assets/images/home_images/camp_5.jpg',
      location: 'Karsog',
      rating: 4.4,
      reviewCount: 33,
      pricePerNight: 2900,
      category: 'Camping',
      isFavorite: true,
      isLiveDeal: false,
    ),
  ].obs;
}