import 'package:get/state_manager.dart';
import 'package:last_minutes_deal/deals/domain/entities/deal_entity.dart';

class DealHomeController extends GetxController {
  final RxList<DealEntity> hotels = <DealEntity>[
    const DealEntity(
      id: 'hotel_1',
      name: 'Hotel Horizon',
      imageUrl: 'assets/images/home_images/hotels/hotel_1.jpg',
      location: 'Lonavala,',
      rating: 4.0,
      reviewCount: 23,
      pricePerNight: 2680,
      category: 'Hotel',
    ),
    const DealEntity(
      id: 'hotel_2',
      name: 'Hotel O Regency',
      imageUrl: 'assets/images/home_images/hotels/hotel_2.jpg',
      location: 'Pune,',
      rating: 3.1,
      reviewCount: 70,
      pricePerNight: 1400,
      category: 'Hotel',
    ),
    const DealEntity(
      id: 'hotel_3',
      name: 'The Heritage Stay',
      imageUrl: 'assets/images/home_images/hotels/hotel_3.jpg',
      location: 'Mahabaleshwar,',
      rating: 4.5,
      reviewCount: 112,
      pricePerNight: 3200,
      category: 'Hotel',
    ),
    const DealEntity(
      id: 'hotel_4',
      name: 'Urban Suites',
      imageUrl: 'assets/images/home_images/hotels/hotel_4.jpg',
      location: 'Mumbai,',
      rating: 4.2,
      reviewCount: 88,
      pricePerNight: 4100,
      category: 'Hotel',
    ),
  ].obs;

  final RxList<DealEntity> resorts = <DealEntity>[
    const DealEntity(
      id: 'resort_1',
      name: 'Lagoon Palm Resort',
      imageUrl: 'assets/images/home_images/resorts/resort_1.jpg',
      location: 'Goa,',
      rating: 4.5,
      reviewCount: 94,
      pricePerNight: 8500,
      category: 'Resort',
    ),
    const DealEntity(
      id: 'resort_2',
      name: 'Azure Water Villa Resort',
      imageUrl: 'assets/images/home_images/resorts/resort_2.jpg',
      location: 'Maldives,',
      rating: 4.9,
      reviewCount: 156,
      pricePerNight: 35000,
      category: 'Resort',
    ),
    const DealEntity(
      id: 'resort_3',
      name: 'Seaside Breeze Resort',
      imageUrl: 'assets/images/home_images/resorts/resort_3.jpg',
      location: 'Kovalam,',
      rating: 4.7,
      reviewCount: 118,
      pricePerNight: 12000,
      category: 'Resort',
    ),
    const DealEntity(
      id: 'resort_4',
      name: 'Splash World Park & Resort',
      imageUrl: 'assets/images/home_images/resorts/resort_4.jpg',
      location: 'Lonavala,',
      rating: 4.2,
      reviewCount: 63,
      pricePerNight: 6800,
      category: 'Resort',
    ),
  ].obs;

  final RxList<DealEntity> villas = <DealEntity>[
    const DealEntity(
      id: 'villa_1',
      name: 'Villas_24',
      imageUrl: 'assets/images/home_images/villas/villa_1.jpg',
      location: 'Lonavala,',
      rating: 4.6,
      reviewCount: 87,
      pricePerNight: 20000,
      category: 'Villa',
    ),
    const DealEntity(
      id: 'villa_2',
      name: 'Palace Villa',
      imageUrl: 'assets/images/home_images/villas/villa_2.jpg',
      location: 'Mumbai,',
      rating: 3.7,
      reviewCount: 28,
      pricePerNight: 25000,
      category: 'Villa',
    ),
    const DealEntity(
      id: 'villa_3',
      name: 'Ekostay Palm Villa',
      imageUrl: 'assets/images/home_images/villas/villa_3.jpg',
      location: 'Alibaug,',
      rating: 4.8,
      reviewCount: 104,
      pricePerNight: 18500,
      category: 'Villa',
    ),
    const DealEntity(
      id: 'villa_4',
      name: 'Sunset Grand Villa',
      imageUrl: 'assets/images/home_images/villas/villa_4.jpg',
      location: 'Karjat,',
      rating: 4.3,
      reviewCount: 45,
      pricePerNight: 22000,
      category: 'Villa',
    ),
  ].obs;

  final RxList<DealEntity> campings = <DealEntity>[
    const DealEntity(
      id: 'camp_1',
      name: 'A-Frame Wooden Huts',
      imageUrl: 'assets/images/home_images/campings/camp_1.jpg',
      location: 'Pawna Lake,',
      rating: 4.5,
      reviewCount: 62,
      pricePerNight: 2500,
      category: 'Camping',
    ),
    const DealEntity(
      id: 'camp_2',
      name: 'Forest Treehouse Camp',
      imageUrl: 'assets/images/home_images/campings/camp_2.jpg',
      location: 'Wayanad,',
      rating: 4.7,
      reviewCount: 89,
      pricePerNight: 4200,
      category: 'Camping',
    ),
    const DealEntity(
      id: 'camp_3',
      name: 'Luxury Glamping Bell Tent',
      imageUrl: 'assets/images/home_images/campings/camp_3.jpg',
      location: 'Alibaug,',
      rating: 4.6,
      reviewCount: 41,
      pricePerNight: 3100,
      category: 'Camping',
    ),
    const DealEntity(
      id: 'camp_4',
      name: 'Pine Forest Safari Camp',
      imageUrl: 'assets/images/home_images/campings/camp_4.jpg',
      location: 'Manali,',
      rating: 4.8,
      reviewCount: 115,
      pricePerNight: 3800,
      category: 'Camping',
    ),
    const DealEntity(
      id: 'camp_5',
      name: 'Luxury Dome Pod Stay',
      imageUrl: 'assets/images/home_images/campings/camp_5.jpg',
      location: 'Karsog,',
      rating: 4.4,
      reviewCount: 33,
      pricePerNight: 2900,
      category: 'Camping',
    ),
  ].obs;
}
